CREATE DATABASE IF NOT EXISTS productDB;

USE productDB;

CREATE TABLE IF NOT EXISTS product(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(250) NOT NULL,
    price DECIMAL(10, 2) NOT NULL  
);
